rails-hma/config/routes.rb
Rails.application.routes.draw do
  get 'sensing/codebook'
	root 'application#home'
end

rails-hma/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-hma/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def home
  end
  private
  def get_videos
    files = Dir.glob("public/videos/*").collect!{|c| c.split('/')[2..-1].join('/')}
    return files
  end
  def get_sounds
    files = Dir.glob("public/audio/*.wav").collect!{|c| c.split('/')[2..-1].join('/')[0..-5]}
    return files
  end
  def get_all_sounds
    files = Dir.glob("public/all_audio/*.wav").collect!{|c| c.split('/')[2..-1].join('/')[0..-5]}
    return files
  end
end

rails-hma/app/controllers/sensing_controller.rb
class SensingController < ApplicationController

  def codebook
    render :layout => "wide_app"
  end
end

rails-hma/app/helpers/application_helper.rb
module ApplicationHelper
	def bglyph icon, options={}
		"<span class='#{options[:class]} glyphicon glyphicon-#{icon}' type='#{options[:type]}' title='#{options[:title]}'></span>".html_safe
	end
	def active_class link_path
		current_page?(link_path) ? "active" : ""
	end

end

rails-hma/app/helpers/sensing_helper.rb
module SensingHelper
end

rails-hma/app/views/application/home.html.haml
.ui.grid.stackable.divided
  %img.logo{src: "/logo.png"}
  .eight.wide.column
    %h3.ui.header 
      Hybrid Microgenetic Analysis:
      %br
      %em Using Activity Codebooks to Identify and Characterize Creative Process
    %address
      %strong Cesar Torres, Matthew Jörke, Emily Hill, Eric Paulos
      %br/
      cearto@berkeley.edu, mjoerke@berkeley.edu, emilyhill@berkeley.edu, paulos@berkeley.edu
      %br/

:css
  .logo{
    height: 250px;
  }

rails-hma/app/views/layouts/_navigation.html.haml
.ui.borderless.main.menu
  .ui.text.container
    .header.item
      Eluent
    %a.item{:href => "/", :name => "home"} Home
    .ui.dropdown.item
      Qualitative Analysis
      %i.dropdown.icon
      .menu
        = link_to "Analysis Interface", sensing_codebook_path, :class => "item"

:css
  .navbar{
    background: #ffc20e;
    border-color: #ffc20e;
    border-radius: 0px;
    font-weight: bold;
  }
  .navbar-default .navbar-nav > li > a{
    color: #111;
    font-size: 1.1em;
  }
  #logo {
    position: relative;
    top: -3px;
  }
  /* ACTIVE COLOR */
  .navbar-default .navbar-nav > .active > a, .navbar-default .navbar-nav > .active > a:hover, .navbar-default .navbar-nav > .active > a:focus{
    background: #ffae0e !important;
  }

rails-hma/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    / Standard Meta
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0", :name => "viewport"}

    %title Hybrid Atelier
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"

    - if params[:controller] != "application"
      = stylesheet_link_tag params[:controller], media: "all"
      = javascript_include_tag params[:controller]
    = csrf_meta_tags

  %body
    = render :partial => "/layouts/navigation"
    .ui.container.text
      = yield
    .ui.inverted.vertical.footer.segment
      .ui.center.aligned.container
        / .ui.inverted.section.divider
        %p 
          Copyright © 2009-
          = Time.new.year 
          UC Berkeley • Hybrid Ecologies Lab
        - if false
          .ui.horizontal.inverted.small.divided.link.list
            %a.item{:href => "#"} Site Map
            %a.item{:href => "#"} Contact Us
            %a.item{:href => "#"} Terms and Conditions
            %a.item{:href => "#"} Privacy Policy

:coffeescript
  $ ->
    # fix main menu to page on passing
    $('.main.menu').visibility
      type: 'fixed'
    $('.overlay').visibility
      type: 'fixed'
      offset: 80
    

   
    # show dropdown on hover
    $('.main.menu  .ui.dropdown').dropdown
      on: 'hover'
    
  
  
:css
  body {
    background-color: #FFFFFF;
  }
  .main.container {
    margin-top: 2em;
  }

  .main.menu {
    border-radius: 0;
    border: none;
    box-shadow: none;
    transition:
      box-shadow 0.5s ease,
      padding 0.5s ease
    ;
  }
  .main.menu .item img.logo {
    margin-right: 1.5em;
    width: 4.5em;
  }

  .overlay {
    float: left;
    margin: 0em 3em 1em 0em;
  }
  .overlay .menu {
    position: relative;
    left: 0;
    transition: left 0.5s ease;
  }

  .main.menu.fixed {
    background-color: #FFFFFF;
    border: 1px solid #DDD;
    box-shadow: 0px 3px 5px rgba(0, 0, 0, 0.2);
  }
  .overlay.fixed .menu {
    left: 800px;
  }

  .text.container .left.floated.image {
    margin: 2em 2em 2em -4em;
  }
  .text.container .right.floated.image {
    margin: 2em -4em 2em 2em;
  }
  .ui.footer{
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
  }
  .ui.footer.segment {
    margin: 3em 0em 0em;
    padding: 3em 0em;
  }

rails-hma/app/views/layouts/wide_app.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Eluent
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    - if params[:controller] != "application"
      = stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}

  :coffeescript
    window.ws = new WebStorage()
  %body
    = yield
    .ui.page.dimmer.transition.hidden
      .content
        .ui.segment.inverted
          .image
            - image_tag "/thermopainting.png", {width: 300}
          .ui.massive.text.loader Loading
          


          
          
      
  
  

rails-hma/app/views/sensing/codebook.html.haml
#metadata{src:"/irb/111/sessionmetadata_111.json"}
#left-panel.panel
	.ui.segment#codebook
		.type CODEBOOKS
		.ui.bar
			.left
				%select.ui.dropdown.tiny#codebook-select
					%option{value: "/irb/111/emotion_111.vtt"} Emotion
					%option{value: "/irb/111/jupyter_111.vtt"} Jupyter Interactions
					%option{value: "/irb/111/kinnunen_111.vtt"} Kinnunen
					%option{value: "/irb/111/bio_111.vtt"} Bio
					%option{value: "/irb/111/hr_111.vtt"} Heart Rate
					%option{value: "/irb/111/phasic_111.vtt"} Phasic EDA Activity
					%option{value: "/irb/111/q_111.vtt"} Question
					%option{value: "/irb/111/motion_111.vtt"} Motion
		.codes.buttons
		.group
			.cbook
				/ %img{src:"/irb/datasets/images/emotion_cbook.png"}
			.cgram
				/ %img{src:"/irb/datasets/images/emotion_cgram.png"}
			.cchar
				/ %img{src:"/irb/datasets/images/emotion_char.png"}

		.plot
			.plottitle.chromatogram User Chromatogram
			.plotarea.paper-plot.chromatimeline


	#primary-display.ui.segment.video-display
		.codebar
			.codeword
				.codelabel
		.ui.bar

			.left
				%select.ui.dropdown.fluid
			.right
				%button.ui.button.remove.gray.icon
					%i.ui.icon.remove

		.stage
			%video#main
				%source{:src => "/irb/111/data/screen_111_opt.mp4", :type => "video/mp4"}
				%track{:default => "", :kind => "subtitles", :label => "English subtitles", :src => "/irb/111/motion_111.vtt", :srclang => "en"}
		%h3.ui-widget-header
		.ui.bar.bottom
			.ui#controls
				.ui.buttons.subcontrols.two
					%button.ui.button.tplay.icon
						%i.play.icon

					%button.ui.button.icon.toggle-menu.blue
						%i.icon.move
				.change.ui.buttons.small.subcontrols
					%button.ui.button.aspect{name:1.7777777777777777}
						4:3
					%button.ui.button.tzoomin.icon
						%i.icon.plus
					%button.ui.button.tzoomout.icon
						%i.icon.minus
					%button.ui.button.tleft.icon
						%i.arrow.left.icon
					%button.ui.button.tright.icon
						%i.arrow.right.icon
					%button.ui.button.tup.icon
						%i.arrow.up.icon
					%button.ui.button.tdown.icon
						%i.arrow.down.icon
					%button.ui.button.trotateleft.icon ↻
					%button.ui.button.trotateright.icon ↺
					%button.ui.button.treset.icon reset
	#secondary-display.ui.segment.video-display
		.ui.bar
			.left
				%select.ui.dropdown.fluid
			.right
				%button.ui.button.remove.gray.icon
					%i.ui.icon.remove
		.stage
			%video#secondary
				%source{:src => "/irb/111/data/screen_111_opt.mp4", :type => "video/mp4"}
		%h3.ui-widget-header
		.ui.bar.bottom
			.ui#controls
				.ui.buttons.subcontrols.two
					%button.ui.button.tplay.icon
						%i.play.icon
					%button.ui.button.icon.toggle-menu.blue
						%i.icon.move

				.change.ui.buttons.small.subcontrols
					%button.ui.button.aspect{name:1.7777777777777777}
						4:3
					%button.ui.button.tzoomin.icon
						%i.icon.plus
					%button.ui.button.tzoomout.icon
						%i.icon.minus
					%button.ui.button.tleft.icon
						%i.arrow.left.icon
					%button.ui.button.tright.icon
						%i.arrow.right.icon
					%button.ui.button.tup.icon
						%i.arrow.up.icon
					%button.ui.button.tdown.icon
						%i.arrow.down.icon
					%button.ui.button.trotateleft.icon ↻
					%button.ui.button.trotateright.icon ↺
					%button.ui.button.treset.icon reset

		#controls
#right-panel.panel
	#user-profile.ui.segment.yellow
		.ui.dropdown.fluid.selection#user-select
			.text
				%img.ui.avatar.massive.image
				Jenny Hess
			%i.dropdown.icon
			.menu
				.item.hidden.template
					%img.ui.avatar.massive.image
					%b.user Jenny Hess
					(
					%span.age
					yo )
					%span.hours_programming_per_week
					hr/wk
					%span.years_programming
					yr exp.
					[
					%span.overall_rating
					]
		%br
		.content.ui.container

			.ui.statistics.mini
				.statistic
					.value.age
					.label AGE
				.statistic
					.value.years_programming
					.label YR EXP
				.statistic
					.value.hours_programming_per_week
					.label HR/WK

			%table.table.ui.table.fluid.collapsing.striped.very.compact
				%tr
					%td Background
					%td{colspan: 3}
						.ui.mini.horizontal.divided.list
							.item
								.content.education
							.item
								.content.industry_experience
				%tr
					%td Overall Rating
					%td
						.ui.star.rating.overall_rating{"data-rating":"3"}
					%td Programmed Normally
					%td
						.ui.star.rating.programmed_normally{"data-rating":"3"}
				%tr
					%td Wristband Comfort
					%td
						.ui.star.rating.affected_by_wristband{"data-rating":"3"}
					%td Average Comfort
					%td
						.ui.star.rating.average_comfort{"data-rating":"3"}
				%tr
					%td Programming Background
					%td{colspan: 3}
						.ui.mini.horizontal.divided.list.programming_background_and_style
							.item.template.hidden
								.content.value
				%tr
					%td Familiar Languages
					%td{colspan: 3}
						.ui.mini.horizontal.divided.list.languages
							.item.template.hidden
								.content.value
				%tr
					%td Familiar Concepts
					%td{colspan: 3}
						.ui.mini.horizontal.divided.list.concepts
							.item.template.hidden
								.content.value
				%tr
					%td Domains
					%td{colspan: 3}
						.ui.mini.horizontal.divided.list.domains
							.item.template.hidden
								.content.value




	#bio-data.ui.segment.blue
		.type bio data
		.plot
			.plottitle PHASIC
			.plotarea.paper-plot{src: "/irb/111/phasic_111.json"}
		.plot
			.plottitle HR
			.plotarea.paper-plot{src: "/irb/111/hr_111.json"}
		

	#jupyter-data.ui.segment.red
		.type Jupyter
		.plot
			.plottitle EXECUTE
			.plotarea.paper-plot{src: "/irb/111/execute_111.json"}
		.plot
			.plottitle MOUSE
			.plotarea.paper-plot{src: "/irb/111/mouseevent_111.json"}
		.plot
			.plottitle SAVE
			.plotarea.paper-plot{src: "/irb/111/notebooksaved_111.json"}
		.plot
			.plottitle SELECT
			.plotarea.paper-plot{src: "/irb/111/select_111.json"}
		.plot
			.plottitle TYPING
			.plotarea.paper-plot{src: "/irb/111/textchunk_111.json"}
		
	
	#kinnunen-data.ui.segment.purple
		.type Kinnunen
		.plot
			.plottitle GETTINGSTARTED
			.plotarea.paper-plot{src: "/irb/111/getting-started_111.json"}
		.plot
			.plottitle DEALINGWITHDIFFICULTIES
			.plotarea.paper-plot{src: "/irb/111/dealing-with-difficulties_111.json"}
		.plot
			.plottitle ENCOUNTERINGDIFFICULTIES
			.plotarea.paper-plot{src: "/irb/111/encountering-difficulties_111.json"}
		.plot
			.plottitle FAILING
			.plotarea.paper-plot{src: "/irb/111/failing_111.json"}
		.plot
			.plottitle SUCCEDING
			.plotarea.paper-plot{src: "/irb/111/succeeding_111.json"}
		.plot
			.plottitle SUBMITTING
			.plotarea.paper-plot{src: "/irb/111/submitting_111.json"}
		
	#q-data.ui.segment.red
		.type Task
		.plot
			.plottitle T1-PRINTLOOP
			.plotarea.paper-plot{src: "/irb/111/q1_111.json", color: "red"}
		.plot
			.plottitle T2- DYNAMIC PROGRAMMING
			.plotarea.paper-plot{src: "/irb/111/q2_111.json", color: "green"}
		.plot
			.plottitle T3 - STABLE SORT
			.plotarea.paper-plot{src: "/irb/111/q3_111.json", color: "green"}
		.plot
			.plottitle T4 - TREE TRAVERSAL
			.plotarea.paper-plot{src: "/irb/111/q4_111.json", color: "green"}

	#notes-display.ui.segment.blue
		%select.ui.fluid.dropdown
		#notes.ui{"content-editable": true}
			From retrospective think aloud

:coffeescript
	$ ->
		window.getImage = (id, name)->
			canvas = $('#view-'+id)[0]
			canvas.toBlob (blob)->
			    saveAs(blob, name+".png")

		window.pm = new ProfileManager
			onLoad: ()->
				handlers ()->
					window.ui = new UIManager()
					window.plt = new PlotManager()
					$(".paper-plot").trigger('load')
				$('#'+111).click() # DEFAULT USER
		$("#notes").on 'mousedown', (e)->
			e.stopPropagation()

rails-hma/app/views/sensing/codes.html.haml
#video-container
  .ui.image.centered
    .ui.black.ribbon.label
      Video
    %video.centered{:controls => "", :width => "620"}
      Sorry, your browser doesn't support embedded videos.
.canvas-area
  %canvas#markup

:scss
  $eggshell: #f5f4f0;
  .session{
    position: relative;
    height: 500px;
    width: 100%;
    display: flex;
    align-content: center;
    justify-content: center;
    flex-flow: column nowrap;
  }
  .session > .node { border: solid 1px #CACACA; }
  .session > .node > .label{
    background: #F5F5F5;
  }
  .session > .node > .panel > .node > .label{
    font-size: 0.9em;
    background: #e9e9e9;
  }
  .session > .node > .panel > .node > .panel .label{
    font-size: 0.8em;
    background: #C9C9C9;
    text-transform: uppercase;
  }
  .node{
    flex-grow: 1;
    display: flex;
    align-content: center;
    justify-content: flex-start;
    flex-flow: row nowrap;
  }
  .panel.paper{
    background: #FFF;
    canvas{
      border: 1px solid #F1F1F1;
      max-height: 61px;
    }
  }

  .panel{
    width: 100%;
    flex-grow: 1;
    display: flex;
    align-content: center;
    justify-content: flex-start;
    flex-flow: column nowrap;
  }
  .label{
    font-family: "Adobe Gothic Std";
    text-align: center;
    padding: 2px;
    display: flex;
    flex-flow: column nowrap;
    justify-content: center;
    align-content: center;
    width: 25px;
    overflow: hidden;
    span{
      display: block;
      transform: rotate(-90deg);
    }
  }
  html, body{
      width: 100%;
      height: 100%;
  }
  .canvas-area{
      display: flex;
      width: 100%;
      height: 100%;
      flex-flow: column nowrap;
      justify-content: center;
      align-items: center;
      padding: 30px 0;
      background: $eggshell;
  }
  #video-container{
    padding: 0px;
    position: absolute;
  }
  video{
      min-height: 350px;
      /* max-width: 300px; */
  }
  canvas#markup{
      width: 100%;
      height: 100%;
  }
  canvas#markup[resize]{
    width: 100%;
    height: 100%;
  }
  .hidden{
      display:none !important;
  }

rails-hma/app/views/sensing/ontology.html.haml
:css
	html, body{
		width: 100%;
		height: 100%;
		overflow:hidden;
	}
	.container{
		width: 100%;
		height: 100%;
	}
	canvas{
		width: 100%;
		height: 100%;
	}

.container
	%canvas

rails-hma/app/views/sensing/other_plots.haml
	.plot
		.plottitle EDA
		.plotarea.paper-plot{src: "/irb/111/eda_111.json"}
	.plot
		.plottitle TEMP
		.plotarea.paper-plot{src: "/irb/111/temp_111.json"}
	.plot
		.plottitle SMNA
		.plotarea.paper-plot{src: "/irb/111/smna_111.json"}
#acc-data.ui.segment.red
	.type Motion
	.plot
		.plottitle ACC_X
		.plotarea.paper-plot{src: "/irb/111/acc-x_111.json", color: "red"}
	.plot
		.plottitle ACC_Y
		.plotarea.paper-plot{src: "/irb/111/acc-y_111.json", color: "green"}
	.plot
		.plottitle ACC_Z
		.plotarea.paper-plot{src: "/irb/111/acc-z_111.json", color: "blue"}

rails-hma/app/views/sensing/vid.html.haml
:coffeescript
  $ ->
    $('.vid.button').click (e)->
      file = "/videos/" + $(this).attr('name') 
      $('video').attr('src', file)
    $('#extract').click (e)->
      content = $('textarea').val()
      lines = content.split('\n')
      snippets = _.map lines, (l)->
        times = l.split(" ")
        start = times[0]
        end = times[1]
       
        row = $("<tr>")
        play_cell = $('<td>')
        
        play_button = $('<button>').addClass("ui button red").html(start).attr
            start: start
            end: end
          .click (e)->
            s = parseFloat($(this).attr('start'))
            e = parseFloat($(this).attr('end'))
            vid = $('video')[0]
            vid.currentTime = s
            vid.play()

        play_cell.append(play_button)
        row.append(play_cell)
        row
      $('#table-contents').html(snippets)



.ui.container
  .ui.segment
    .ui.horizontal.list
      - @videos.each do |v|
        .ui.item
          .ui.vid.small.button{:name => v}
            = v.split('.')[0]



.ui.two.column.grid.container
  .column
    .ui.segment
      .ui.video
        %video.ui.centered{:controls => 'controls', :width => "620"}
          Sorry, your browser doesn't support embedded videos.
    .ui.form.segment
      .ui.field
        %textarea.ui
      .ui.button.blue#extract
        EXTRACT
  .column
    %table.ui.celled.padded.table
      %thead
        %tr
          %th Snippet
          %th EDA
          %th BVP
      %tbody#table-contents
        
:css
  video{
      width: 100%;
  }